name: Continues Integration and

on:
  push:
    branches: ["telecom"]
  pull_request:
    branches: ["telecom"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.BRANCH }} && git pull && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
