name: Django CI

on:
  push:
    branches: ["master", "development", "telecom"]
  pull_request:
    branches: ["master", "development", "telecom"]

env:
  DJANGO_SETTINGS_MODULE: config.settings.development
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  BROKER_URL: ${{ secrets.BROKER_URL }}
  RECAPTCHA_V3_PUBLIC_KEY: ${{ secrets.RECAPTCHA_V3_PUBLIC_KEY }}
  RECAPTCHA_V3_PRIVATE_KEY: ${{ secrets.RECAPTCHA_V3_PRIVATE_KEY }}
  RECAPTCHA_V2_PUBLIC_KEY: ${{ secrets.RECAPTCHA_V2_PUBLIC_KEY }}
  RECAPTCHA_V2_PRIVATE_KEY: ${{ secrets.RECAPTCHA_V2_PRIVATE_KEY }}
  SMS_URI: ${{ secrets.SMS_URI }}
  SMS_USERNAME: ${{ secrets.SMS_USERNAME }}
  SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Makemigrations
        run: |
          python manage.py makemigrations
      - name: Migrate
        run: |
          python manage.py migrate
    #   - name: Run Tests
    #     run: |
    #       python manage.py test apps
