name: Docker Image CI

on:
  push:
    branches: ["master", "telecom", "development"]
  pull_request:
    branches: ["master", "telecom", "development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DJANGO_SETTINGS_MODULE=config.settings.production" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "BROKER_URL=${{ secrets.BROKER_URL }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "RECAPTCHA_V3_PUBLIC_KEY=${{ secrets.RECAPTCHA_V3_PUBLIC_KEY }}" >> .env
          echo "RECAPTCHA_V3_PRIVATE_KEY=${{ secrets.RECAPTCHA_V3_PRIVATE_KEY }}" >> .env
          echo "RECAPTCHA_V2_PUBLIC_KEY=${{ secrets.RECAPTCHA_V2_PUBLIC_KEY }}" >> .env
          echo "RECAPTCHA_V2_PRIVATE_KEY=${{ secrets.RECAPTCHA_V2_PRIVATE_KEY }}" >> .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env
          echo "SMS_URI=${{ secrets.SMS_URI }}" >> .env
          echo "SMS_USERNAME=${{ secrets.SMS_USERNAME }}" >> .env
          echo "SMS_PASSWORD=${{ secrets.SMS_PASSWORD }}" >> .env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Docker compose up
        run: docker compose up -d

      - name: Makemigrations
        run: docker compose exec web python manage.py makemigrations

      - name: Migrate
        run: docker compose exec web python manage.py migrate
